### ISSUE TITLE
AppImage file fails with various errors on Linux Mint 19.2

### ISSUE THREAD

**Issue by bitsgalore** [webrecorder/webrecorder-desktop#30]
I just downloaded the v. 2.0.1 AppImage and made it executable. Since nothing happened after double-clicking on the file, I tried to launch it from a terminal window using:

    ./webrecorder-2.0.1.AppImage

This gave me the following output:

```
    Dat Share api server listening on
    http://localhost:44927
    └── /
        ├── s
        │   ├── wagger (GET)
        │   │   └── / (GET)
        │   │       ├── json (GET)
        │   │       ├── yaml (GET)
        │   │       ├── static/
        │   │       │   └── * (GET)
        │   │       └── * (GET)
        │   ├── hare (POST)
        │   └── ync (POST)
        ├── init (POST)
        ├── unshare (POST)
        └── num
            ├── Sharing (GET)
            └── Dats (GET)

    --no-browser --loglevel info -d /home/johan/Documents/Webrecorder-Data -u johan --port 0 --behaviors-tarfile /tmp/.mount_webrecQHAGW7/resources/python-binaries/behaviors.tar.gz --dat-share-port 44927
    [5405] Failed to execute script webrecorder_full

    Traceback (most recent call last):
      File "redis/connection.py", line 484, in connect
      File "redis/connection.py", line 541, in _connect
      File "redis/connection.py", line 529, in _connect
      File "gevent/_socket3.py", line 335, in connect
    ConnectionRefusedError: [Errno 111] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "redis/client.py", line 667, in execute_command
      File "redis/connection.py", line 610, in send_command
      File "redis/connection.py", line 585, in send_packed_command
      File "redis/connection.py", line 489, in connect
    redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:7679. Connection refused.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "redis/connection.py", line 484, in connect
      File "redis/connection.py", line 541, in _connect
      File "redis/connection.py", line 529, in _connect
      File "gevent/_socket3.py", line 335, in connect
    ConnectionRefusedError: [Errno 111] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "webrecorder/standalone/localredisserver.py", line 109, in start
      File "webrecorder/standalone/localredisserver.py", line 104, in _init_redis
      File "redis/client.py", line 711, in client_setname
      File "redis/client.py", line 673, in execute_command
      File "redis/connection.py", line 610, in send_command
      File "redis/connection.py", line 585, in send_packed_command
      File "redis/connection.py", line 489, in connect
    redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:7679. Connection refused.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "webrecorder/standalone/webrecorder_full.py", line 132, in <module>
      File "webrecorder/standalone/standalone.py", line 119, in main
      File "webrecorder/standalone/webrecorder_full.py", line 36, in __init__
      File "webrecorder/standalone/standalone.py", line 49, in __init__
      File "webrecorder/standalone/webrecorder_full.py", line 69, in _runner_init
      File "webrecorder/standalone/localredisserver.py", line 112, in start
      File "webrecorder/standalone/localredisserver.py", line 170, in create_redis_server
      File "site-packages/psutil-5.6.3-py3.6-linux-x86_64.egg/psutil/__init__.py", line 1431, in __init__
      File "gevent/subprocess.py", line 627, in __init__
      File "gevent/subprocess.py", line 1505, in _execute_child
    FileNotFoundError: [Errno 2] No such file or directory: 'redis-server'

    no process
```
## System info

I'm getting this result on a machine with Linux Mint 19.2 (Tina), equivalent to Ubuntu Bionic. Earlier today I got the same problem while trying to run it on another machine with an older Mint version (18.3 if I recalll correctly).

**Comment by bitsgalore** [comment]
Closing because I only now see the comment on the redis requirement in the readme, missed that earlier!
